apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  PUID: "1000"
  PGID: "1000"
  FLATNOTES_AUTH_TYPE: "password"
  FLATNOTES_USERNAME: "username"
  FLATNOTES_PASSWORD: "password"
  FLATNOTES_SECRET_KEY: "LongRandomSeriesOfCharacters"
  FLATNOTES_HOST: "0.0.0.0"
  FLATNOTES_PORT: "8080"