apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  username: "dXNlcm5hbWU="  # echo -n "username" | base64
  password: "cGFzc3dvcmQ="  # echo -n "password" | base64
  secret_key: "UmFuZG9tS2V5" # echo -n "RandomKey" | base64