---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-1-conf
data:
  index.html: |
    Hello from nginx-1!

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-2-conf
data:
  index.html: |
    Hello from nginx-2!

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
      name: http-port
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: index-volume
  volumes:
  - name: index-volume
    configMap:
      name: nginx-1-conf
      items:
      - key: index.html
        path: index.html

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
      name: http-port
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: index-volume
  volumes:
  - name: index-volume
    configMap:
      name: nginx-2-conf
      items:
      - key: index.html
        path: index.html

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: http-port
    nodePort: 30080

# Воспроизвести данный пример, используя только один ConfigMap с двумя ключами.

  # ---
  # apiVersion: v1
  # kind: ConfigMap
  # metadata:
  #   name: nginx
  # data:
  #   index-1.html: |
  #     Hello from nginx-1!
  #   index-2.html: |
  #     Hello from nginx-2!

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-1
#   labels:
#     appName: nginx
# spec:
#   ...
#   volumes:
#   - name: index
#     configMap:
#       name: nginx
#       items:
#       - key: index-1.html
#         path: index.html

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-2
#   labels:
#     appName: nginx
# spec:
#   ...
#   volumes:
#   - name: index
#     configMap:
#       name: nginx
#       items:
#       - key: index-2.html
#         path: index.html