---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  index.html: |
    Nginx!

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    appName: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
      name: http-port
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: index-volume
  volumes:
  - name: index-volume
    configMap:
      name: nginx-conf
      items:
      - key: index.html
        path: index.html
      - key: 1.html
        path: 1.html
      - key: 2.html
        path: 2.html

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    appName: nginx
  ports:
  - port: 80
    targetPort: http-port
    nodePort: 30080
