---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-serviceaccount
  namespace: demo-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: demo-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] # "create", "update", "delete", 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: demo-namespace
subjects:
- kind: ServiceAccount
  name: demo-serviceaccount
  namespace: demo-namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo-namespace
spec:
  serviceAccountName: demo-serviceaccount
  containers:
  - name: demo-container
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]



# kubectl get pods ---> OK
# kubectl get pods -n default ---> NOT OK
# kubectl run test-pod --image=nginx ---> NOT OK

# Обновить права: добавить "create"
# kubectl run test-pod --image=nginx ---> OK
# kubectl get pods ---> OK
# kubectl delete pod test-pod ---> NOT OK