---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flatnotes-conf
data:
  PUID: "1000"
  PGID: "1000"
  FLATNOTES_AUTH_TYPE: "password"

---
apiVersion: v1
kind: Secret
metadata:
  name: flatnotes-secret
type: Opaque
data:
  username: "dXNlcm5hbWU="  # echo -n "username" | base64
  password: "cGFzc3dvcmQ="  # echo -n "password" | base64
  secret_key: "UmFuZG9tS2V5" # echo -n "RandomKey" | base64
  
---
apiVersion: v1
kind: Pod
metadata:
  name: flatnotes-pod
  labels:
    appName: flatnotes
spec:
  containers:
  - name: flatnotes
    image: dullage/flatnotes:latest
    envFrom:
      - configMapRef:
          name: flatnotes-conf
    env:
    - name: FLATNOTES_USERNAME
      valueFrom:
        secretKeyRef:
          name: flatnotes-secret
          key: username
    - name: FLATNOTES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: flatnotes-secret
          key: password
    - name: FLATNOTES_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: flatnotes-secret
          key: secret_key
    ports:
    - containerPort: 8080
      name: http-port

---
apiVersion: v1
kind: Service
metadata:
  name: flatnotes-nodeport-service
spec:
  type: NodePort
  selector:
    appName: flatnotes
  ports:
  - port: 8080
    targetPort: http-port
    nodePort: 30080
    