---
apiVersion: v1
kind: ConfigMap # ConfigMap монтируется только в режиме readOnly
metadata:
  name: flatnotes-conf
data:
  PUID: "1000"
  PGID: "1000"
  FLATNOTES_AUTH_TYPE: "password"
  FLATNOTES_USERNAME: "username"
  FLATNOTES_PASSWORD: "password"
  FLATNOTES_SECRET_KEY: "LongRandomSeriesOfCharacters"

---
apiVersion: v1
kind: Pod
metadata:
  name: flatnotes-pod
  labels:
    appName: flatnotes
spec:
  containers:
  - name: flatnotes
    image: dullage/flatnotes:latest
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: flatnotes-conf
    volumeMounts: 
    - mountPath: /data # https://github.com/dullage/flatnotes?tab=readme-ov-file#self-hosted
      name: nfs-volume
  volumes:
  - name: nfs-volume
    nfs:
      server: 192.168.0.1
      path: /nfs/flatnotes

---
apiVersion: v1
kind: Service
metadata:
  name: flatnotes-nodeport-service
spec:
  type: NodePort
  selector:
    appName: flatnotes
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

# Установить сервер: apt install -y nfs-kernel-server
# На все ноды установить: apt install -y nfs-common
# На сервере: mkdir -p /nfs/flatnotes
# На сервере: echo "/nfs/flatnotes  192.168.0.0/24(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
# На сервере: exportfs -a