---
apiVersion: batch/v1
kind: Job
metadata:
  name: flog
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: flog
          image: golang # https://github.com/mingrammer/flog (проблемы с запуском из готового образа)
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /logs
          command: ["sleep", "36000"]
      volumes:
        - name: logs
          nfs:
            server: 192.168.0.1
            path: /nfs/nginx-logs
      restartPolicy: Never
  backoffLimit: 0

# kubectl -n logging exec -it flog-l7vqc -- /bin/bash
# go install github.com/mingrammer/flog@latest
# flog -t log -f apache_combined -o /logs/generated.log -n 10000 -d 500ms -f json -w