apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        flush 1
        gaemon off
        log_level debug
        hot_reload on
    @INCLUDE inputs.conf
    @INCLUDE outputs.conf

  inputs.conf: |
    [INPUT]
        name node_exporter_metrics
        tag node_metrics
        scrape_interval 2
        path.procfs /host/proc
        path.sysfs /host/sys

  outputs.conf: |
    [OUTPUT]
        name  prometheus_exporter
        match node_metrics
        host  0.0.0.0
        port  2021
