apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: logging
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: fluentbit
        scrape_interval: 5s
        static_configs:
          - targets: ['fluentbit:2021']
        metrics_path: '/api/v1/metrics/prometheus'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      namespace: logging
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus
          configMap:
            name: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: logging
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
