apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: logging
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: fluentbit
      scrape_interval: 5s
      static_configs:
      - targets:
        - fluentbit:2021