apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    # Если данное приложение будет удалено, то все связанные с ним тоже удалятся
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://192.168.250.232:3000/user1/argocd-testing.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      
      # Если удалить зависимое приложение, то оно будет восстановлено
      selfHeal: true