apiVersion: v1
    ---
    kind: Namespace
    metadata:
      name: argocd-nginx

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: argocd-nginx
      namespace: argocd-nginx
      labels:
        app: argocd-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-nginx
      namespace: argocd-nginx
    spec:
      type: NodePort
      selector:
        app: argocd-nginx
      ports:
      - port: 80
        targetPort: 80
        nodePort: 30080